export const mockProducts = [
  {
    id: 1,
    username: 'smalatalant0',
    avatar: 'https://robohash.org/nemononquibusdam.png?size=50x50&set=set1',
    title: 'odio curabitur convallis duis consequat',
    photo: '/images/products/1.jpg',
    state: 'Used',
    price: '$90.09',
    uploaded_at: '2021-11-17T20:46:55Z',
    protected: true,
    likes: 20,
  },
  {
    id: 2,
    username: 'cshuter1',
    avatar:
      'https://robohash.org/estconsequunturitaque.png?size=50x50&set=set1',
    title:
      'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor',
    photo: '/images/products/2.jpg',
    state: 'Brand New',
    price: '$17.86',
    uploaded_at: '2021-11-17T15:46:55Z',
    protected: false,
    likes: 12,
  },
  {
    id: 3,
    username: 'kpitford2',
    avatar: 'https://robohash.org/voluptasteneturquo.png?size=50x50&set=set1',
    title: 'pulvinar sed nisl nunc rhoncus dui vel sem',
    photo: '/images/products/3.jpg',
    state: 'Like New',
    price: '$74.31',
    uploaded_at: '2021-09-23T21:23:13Z',
    protected: false,
    likes: 6,
  },
  {
    id: 4,
    username: 'aandric3',
    avatar:
      'https://robohash.org/laudantiumnobisvoluptatem.png?size=50x50&set=set1',
    title: 'donec semper sapien a libero nam',
    photo: '/images/products/4.jpg',
    state: 'Brand New',
    price: '$67.33',
    uploaded_at: '2021-03-05T18:39:49Z',
    protected: true,
    likes: 6,
  },
  {
    id: 5,
    username: 'ahewlings4',
    avatar: 'https://robohash.org/quiquossit.png?size=50x50&set=set1',
    title: 'suscipit nulla elit',
    photo: '/images/products/5.jpg',
    state: 'Used',
    price: '$68.93',
    uploaded_at: '2021-12-09T00:02:54Z',
    protected: false,
    likes: 14,
  },
  {
    id: 6,
    username: 'pgile5',
    avatar: 'https://robohash.org/adipiscirationeillo.png?size=50x50&set=set1',
    title: 'hac habitasse platea dictumst maecenas ut massa',
    photo: '/images/products/6.jpg',
    state: 'Well Used',
    price: '$61.81',
    uploaded_at: '2021-06-09T15:50:14Z',
    protected: false,
    likes: 20,
  },
  {
    id: 7,
    username: 'bstaniforth6',
    avatar:
      'https://robohash.org/doloremassumendaaccusamus.png?size=50x50&set=set1',
    title: 'nullam varius nulla',
    photo: '/images/products/7.jpg',
    state: 'Like New',
    price: '$32.02',
    uploaded_at: '2021-09-16T01:47:06Z',
    protected: true,
    likes: 10,
  },
  {
    id: 8,
    username: 'sstrank7',
    avatar: 'https://robohash.org/quiquaedebitis.png?size=50x50&set=set1',
    title:
      'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus',
    photo: '/images/products/8.jpg',
    state: 'Brand New',
    price: '$75.31',
    uploaded_at: '2021-05-20T22:27:21Z',
    protected: true,
    likes: 13,
  },
  {
    id: 9,
    username: 'scronin8',
    avatar: 'https://robohash.org/voluptatemteneturin.png?size=50x50&set=set1',
    title: 'eget eleifend luctus ultricies',
    photo: '/images/products/9.jpg',
    state: 'Like New',
    price: '$5.20',
    uploaded_at: '2021-07-10T09:40:34Z',
    protected: false,
    likes: 3,
  },
  {
    id: 10,
    username: 'ekeggins9',
    avatar: 'https://robohash.org/veritatisutratione.png?size=50x50&set=set1',
    title: 'eget massa tempor convallis nulla neque libero',
    photo: '/images/products/10.jpg',
    state: 'Well Used',
    price: '$67.61',
    uploaded_at: '2021-08-15T21:28:53Z',
    protected: true,
    likes: 2,
  },
  {
    id: 11,
    username: 'rlucioa',
    avatar: 'https://robohash.org/quinumquamdeleniti.png?size=50x50&set=set1',
    title: 'duis at velit',
    photo: '/images/products/11.jpg',
    state: 'New',
    price: '$13.04',
    uploaded_at: '2021-12-26T21:14:19Z',
    protected: true,
    likes: 14,
  },
  {
    id: 12,
    username: 'abarthb',
    avatar:
      'https://robohash.org/doloremquelaboriosamsit.png?size=50x50&set=set1',
    title: 'ligula nec sem duis aliquam convallis',
    photo: '/images/products/12.jpg',
    state: 'Brand New',
    price: '$61.07',
    uploaded_at: '2021-10-06T03:22:00Z',
    protected: false,
    likes: 14,
  },
  {
    id: 13,
    username: 'wbreedyc',
    avatar: 'https://robohash.org/debitiseumquam.png?size=50x50&set=set1',
    title:
      'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu',
    photo: '/images/products/13.jpg',
    state: 'New',
    price: '$59.85',
    uploaded_at: '2021-11-21T18:55:19Z',
    protected: true,
    likes: 5,
  },
  {
    id: 14,
    username: 'ekleesd',
    avatar: 'https://robohash.org/laboriosamearepellat.png?size=50x50&set=set1',
    title:
      'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et',
    photo: '/images/products/14.jpg',
    state: 'New',
    price: '$75.12',
    uploaded_at: '2021-09-24T08:10:51Z',
    protected: false,
    likes: 18,
  },
  {
    id: 15,
    username: 'mduignane',
    avatar: 'https://robohash.org/utipsaet.png?size=50x50&set=set1',
    title:
      'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla',
    photo: '/images/products/15.jpg',
    state: 'Well Used',
    price: '$59.29',
    uploaded_at: '2021-12-16T04:05:44Z',
    protected: false,
    likes: 7,
  },
  {
    id: 16,
    username: 'pdambrosiof',
    avatar: 'https://robohash.org/evenietblanditiisvel.png?size=50x50&set=set1',
    title: 'enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus',
    photo: '/images/products/16.jpg',
    state: 'Like New',
    price: '$68.13',
    uploaded_at: '2022-01-24T15:49:05Z',
    protected: false,
    likes: 19,
  },
  {
    id: 17,
    username: 'mcohrsg',
    avatar: 'https://robohash.org/oditdoloresdolor.png?size=50x50&set=set1',
    title: 'purus eu magna vulputate luctus',
    photo: '/images/products/17.jpg',
    state: 'Used',
    price: '$49.40',
    uploaded_at: '2021-11-26T16:58:15Z',
    protected: false,
    likes: 9,
  },
  {
    id: 18,
    username: 'bvanyushinh',
    avatar: 'https://robohash.org/eospariaturiusto.png?size=50x50&set=set1',
    title: 'curabitur convallis duis consequat dui nec',
    photo: '/images/products/18.jpg',
    state: 'Used',
    price: '$39.70',
    uploaded_at: '2021-03-20T11:04:46Z',
    protected: true,
    likes: 16,
  },
  {
    id: 19,
    username: 'faylwardi',
    avatar:
      'https://robohash.org/voluptatemipsaquibusdam.png?size=50x50&set=set1',
    title: 'eu massa donec dapibus duis',
    photo: '/images/products/19.jpg',
    state: 'Like New',
    price: '$76.50',
    uploaded_at: '2021-08-03T02:38:25Z',
    protected: false,
    likes: 18,
  },
  {
    id: 20,
    username: 'obrymnerj',
    avatar: 'https://robohash.org/autemquicum.png?size=50x50&set=set1',
    title: 'eu mi nulla ac enim in tempor turpis nec',
    photo: '/images/products/20.jpg',
    state: 'Brand New',
    price: '$81.04',
    uploaded_at: '2021-08-24T04:42:24Z',
    protected: true,
    likes: 1,
  },
  {
    id: 21,
    username: 'emellingsk',
    avatar: 'https://robohash.org/quiaaliquidinventore.png?size=50x50&set=set1',
    title: 'pellentesque ultrices mattis odio donec vitae nisi',
    photo: '/images/products/21.jpg',
    state: 'Brand New',
    price: '$89.27',
    uploaded_at: '2021-12-15T16:45:47Z',
    protected: true,
    likes: 8,
  },
  {
    id: 22,
    username: 'praml',
    avatar: 'https://robohash.org/modietet.png?size=50x50&set=set1',
    title: 'ultrices posuere cubilia curae nulla',
    photo: '/images/products/22.jpg',
    state: 'Brand New',
    price: '$61.45',
    uploaded_at: '2021-10-01T14:01:33Z',
    protected: false,
    likes: 18,
  },
  {
    id: 23,
    username: 'cmastrantonem',
    avatar: 'https://robohash.org/dolorumquiseos.png?size=50x50&set=set1',
    title: 'pede morbi porttitor lorem id ligula suspendisse ornare consequat',
    photo: '/images/products/23.jpg',
    state: 'Well Used',
    price: '$70.25',
    uploaded_at: '2022-02-13T03:13:02Z',
    protected: true,
    likes: 12,
  },
  {
    id: 24,
    username: 'ccattlown',
    avatar:
      'https://robohash.org/doloremquepariaturomnis.png?size=50x50&set=set1',
    title: 'maecenas rhoncus aliquam lacus morbi',
    photo: '/images/products/24.jpg',
    state: 'New',
    price: '$49.00',
    uploaded_at: '2022-01-31T17:20:57Z',
    protected: true,
    likes: 0,
  },
  {
    id: 25,
    username: 'rgeertseno',
    avatar:
      'https://robohash.org/asperioresiurevoluptatem.png?size=50x50&set=set1',
    title: 'luctus et ultrices posuere cubilia curae mauris viverra',
    photo: '/images/products/25.jpg',
    state: 'Used',
    price: '$88.00',
    uploaded_at: '2021-07-30T02:28:01Z',
    protected: true,
    likes: 3,
  },
  {
    id: 26,
    username: 'pnewburnp',
    avatar: 'https://robohash.org/uteaquedoloribus.png?size=50x50&set=set1',
    title: 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus',
    photo: '/images/products/26.jpg',
    state: 'Well Used',
    price: '$11.61',
    uploaded_at: '2021-08-25T00:26:43Z',
    protected: false,
    likes: 4,
  },
  {
    id: 27,
    username: 'tstonehamq',
    avatar: 'https://robohash.org/sintoptioadipisci.png?size=50x50&set=set1',
    title:
      'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum',
    photo: '/images/products/27.jpg',
    state: 'Like New',
    price: '$20.54',
    uploaded_at: '2021-04-05T09:31:20Z',
    protected: false,
    likes: 0,
  },
  {
    id: 28,
    username: 'jduckettr',
    avatar:
      'https://robohash.org/maximeaccusamusincidunt.png?size=50x50&set=set1',
    title: 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed',
    photo: '/images/products/28.jpg',
    state: 'Well Used',
    price: '$49.62',
    uploaded_at: '2022-02-04T10:20:36Z',
    protected: false,
    likes: 12,
  },
  {
    id: 29,
    username: 'hcoxens',
    avatar: 'https://robohash.org/autreiciendis.png?size=50x50&set=set1',
    title:
      'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est',
    photo: '/images/products/29.jpg',
    state: 'Used',
    price: '$70.05',
    uploaded_at: '2021-05-18T14:09:42Z',
    protected: true,
    likes: 17,
  },
  {
    id: 30,
    username: 'vtitmust',
    avatar: 'https://robohash.org/namnumquamqui.png?size=50x50&set=set1',
    title: 'massa id lobortis',
    photo: '/images/products/30.jpg',
    state: 'New',
    price: '$13.01',
    uploaded_at: '2021-10-02T13:49:12Z',
    protected: true,
    likes: 0,
  },
  {
    id: 31,
    username: 'esukbhansu',
    avatar: 'https://robohash.org/quisautinventore.png?size=50x50&set=set1',
    title:
      'quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus',
    photo: '/images/products/31.jpg',
    state: 'Like New',
    price: '$14.38',
    uploaded_at: '2022-01-20T03:29:10Z',
    protected: false,
    likes: 8,
  },
  {
    id: 32,
    username: 'nlivingstonv',
    avatar: 'https://robohash.org/etmollitiadolor.png?size=50x50&set=set1',
    title: 'vestibulum sed magna at nunc commodo placerat praesent blandit nam',
    photo: '/images/products/32.jpg',
    state: 'Used',
    price: '$52.81',
    uploaded_at: '2021-10-21T21:59:00Z',
    protected: false,
    likes: 10,
  },
  {
    id: 33,
    username: 'sdunckleew',
    avatar: 'https://robohash.org/eumtemporibusrerum.png?size=50x50&set=set1',
    title: 'duis bibendum felis sed',
    photo: '/images/products/33.jpg',
    state: 'Brand New',
    price: '$7.53',
    uploaded_at: '2021-12-04T05:58:17Z',
    protected: true,
    likes: 11,
  },
  {
    id: 34,
    username: 'lmccabex',
    avatar: 'https://robohash.org/verooditut.png?size=50x50&set=set1',
    title:
      'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet',
    photo: '/images/products/34.jpg',
    state: 'Like New',
    price: '$70.14',
    uploaded_at: '2021-08-16T03:15:59Z',
    protected: false,
    likes: 19,
  },
  {
    id: 35,
    username: 'cdanielskyy',
    avatar: 'https://robohash.org/asperioresnobisut.png?size=50x50&set=set1',
    title: 'sed ante vivamus tortor duis mattis egestas metus aenean',
    photo: '/images/products/35.jpg',
    state: 'Used',
    price: '$50.05',
    uploaded_at: '2021-10-22T04:27:37Z',
    protected: true,
    likes: 6,
  },
  {
    id: 36,
    username: 'jjeffreysz',
    avatar: 'https://robohash.org/autnumquamdolorem.png?size=50x50&set=set1',
    title:
      'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus',
    photo: '/images/products/36.jpg',
    state: 'Brand New',
    price: '$35.13',
    uploaded_at: '2022-02-16T10:16:32Z',
    protected: true,
    likes: 2,
  },
  {
    id: 37,
    username: 'mgalfour10',
    avatar: 'https://robohash.org/hicmolestiaeet.png?size=50x50&set=set1',
    title: 'consequat morbi a ipsum integer',
    photo: '/images/products/37.jpg',
    state: 'Well Used',
    price: '$24.72',
    uploaded_at: '2021-07-27T13:07:27Z',
    protected: false,
    likes: 20,
  },
  {
    id: 38,
    username: 'vlamie11',
    avatar:
      'https://robohash.org/quisquamaliasexcepturi.png?size=50x50&set=set1',
    title: 'nec dui luctus rutrum',
    photo: '/images/products/38.jpg',
    state: 'Brand New',
    price: '$92.03',
    uploaded_at: '2021-12-10T19:14:57Z',
    protected: true,
    likes: 7,
  },
  {
    id: 39,
    username: 'pmcmarquis12',
    avatar:
      'https://robohash.org/aperiamconsequaturexcepturi.png?size=50x50&set=set1',
    title: 'vel lectus in quam fringilla',
    photo: '/images/products/39.jpg',
    state: 'Like New',
    price: '$59.58',
    uploaded_at: '2021-12-26T14:14:57Z',
    protected: false,
    likes: 10,
  },
  {
    id: 40,
    username: 'nbrafferton13',
    avatar:
      'https://robohash.org/laboriosamvoluptatemqui.png?size=50x50&set=set1',
    title:
      'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor',
    photo: '/images/products/40.jpg',
    state: 'Like New',
    price: '$36.10',
    uploaded_at: '2021-12-18T22:43:37Z',
    protected: true,
    likes: 10,
  },
  {
    id: 41,
    username: 'cvanleeuwen14',
    avatar: 'https://robohash.org/quiadebitissint.png?size=50x50&set=set1',
    title:
      'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada',
    photo: '/images/products/41.jpg',
    state: 'New',
    price: '$27.71',
    uploaded_at: '2021-05-27T18:22:47Z',
    protected: false,
    likes: 14,
  },
  {
    id: 42,
    username: 'lkewish15',
    avatar: 'https://robohash.org/nonquiset.png?size=50x50&set=set1',
    title:
      'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in',
    photo: '/images/products/42.jpg',
    state: 'Brand New',
    price: '$76.73',
    uploaded_at: '2021-05-16T04:47:31Z',
    protected: true,
    likes: 11,
  },
  {
    id: 43,
    username: 'gtumbelty16',
    avatar: 'https://robohash.org/quispossimusdolores.png?size=50x50&set=set1',
    title: 'nisi vulputate nonummy',
    photo: '/images/products/43.jpg',
    state: 'New',
    price: '$69.98',
    uploaded_at: '2021-08-02T22:46:45Z',
    protected: false,
    likes: 5,
  },
  {
    id: 44,
    username: 'skoppeck17',
    avatar: 'https://robohash.org/etquisunt.png?size=50x50&set=set1',
    title: 'sit amet nulla quisque arcu libero rutrum ac',
    photo: '/images/products/44.jpg',
    state: 'New',
    price: '$58.87',
    uploaded_at: '2021-11-13T06:56:16Z',
    protected: true,
    likes: 10,
  },
  {
    id: 45,
    username: 'gnewman18',
    avatar:
      'https://robohash.org/voluptatibuslaboriosamfacere.png?size=50x50&set=set1',
    title: 'congue vivamus metus',
    photo: '/images/products/45.jpg',
    state: 'Well Used',
    price: '$33.43',
    uploaded_at: '2021-03-22T17:36:18Z',
    protected: false,
    likes: 0,
  },
  {
    id: 46,
    username: 'amines19',
    avatar:
      'https://robohash.org/aliasadipisciarchitecto.png?size=50x50&set=set1',
    title: 'id ornare imperdiet sapien urna pretium nisl',
    photo: '/images/products/46.jpg',
    state: 'Well Used',
    price: '$42.40',
    uploaded_at: '2021-06-25T00:40:20Z',
    protected: true,
    likes: 12,
  },
  {
    id: 47,
    username: 'pcrampin1a',
    avatar: 'https://robohash.org/nonquibusdamminus.png?size=50x50&set=set1',
    title:
      'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis',
    photo: '/images/products/47.jpg',
    state: 'Well Used',
    price: '$98.13',
    uploaded_at: '2022-01-27T17:23:39Z',
    protected: true,
    likes: 10,
  },
  {
    id: 48,
    username: 'fdarrach1b',
    avatar: 'https://robohash.org/cumquerepudiandaeeum.png?size=50x50&set=set1',
    title: 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar',
    photo: '/images/products/48.jpg',
    state: 'Brand New',
    price: '$68.60',
    uploaded_at: '2021-08-23T07:22:11Z',
    protected: false,
    likes: 9,
  },
  {
    id: 49,
    username: 'vtrathan1c',
    avatar: 'https://robohash.org/itaquenamdoloremque.png?size=50x50&set=set1',
    title: 'nulla ac enim in',
    photo: '/images/products/49.jpg',
    state: 'Brand New',
    price: '$51.62',
    uploaded_at: '2021-05-19T00:34:44Z',
    protected: true,
    likes: 0,
  },
  {
    id: 50,
    username: 'eclaypole1d',
    avatar: 'https://robohash.org/autemquidemsed.png?size=50x50&set=set1',
    title: 'sollicitudin ut suscipit a feugiat',
    photo: '/images/products/50.jpg',
    state: 'Like New',
    price: '$6.29',
    uploaded_at: '2021-09-17T10:28:15Z',
    protected: false,
    likes: 17,
  },
];
