export const mockProducts = [
  {
    id: 1,
    username: 'jgeorge0',
    avatar: 'https://robohash.org/praesentiumabmodi.png?size=50x50&set=set1',
    title: 'Other diagnostic procedures on liver',
    photo: null,
    state: 'Used',
    price: '$24.84',
    uploaded_at: '2021-05-25T17:13:16Z',
    protected: false,
    likes: 16,
  },
  {
    id: 2,
    username: 'tloncaster1',
    avatar: 'https://robohash.org/corporisdolorcumque.png?size=50x50&set=set1',
    title: 'Lymphangiogram of upper limb',
    photo: null,
    state: 'Well Used',
    price: '$29.87',
    uploaded_at: '2021-10-18T14:43:26Z',
    protected: false,
    likes: 20,
  },
  {
    id: 3,
    username: 'sscrowston2',
    avatar:
      'https://robohash.org/nesciuntfugaveritatis.png?size=50x50&set=set1',
    title:
      'Replacement of any type pacemaker device with single-chamber device, not specified as rate responsive',
    photo: null,
    state: 'New',
    price: '$21.93',
    uploaded_at: '2021-05-08T18:38:29Z',
    protected: true,
    likes: 15,
  },
  {
    id: 4,
    username: 'htrevers3',
    avatar: 'https://robohash.org/sitplaceatut.png?size=50x50&set=set1',
    title: 'Other external maxillary antrotomy',
    photo: null,
    state: 'Like New',
    price: '$35.52',
    uploaded_at: '2021-03-18T12:53:05Z',
    protected: false,
    likes: 4,
  },
  {
    id: 5,
    username: 'hhindes4',
    avatar: 'https://robohash.org/culparepellatmagni.png?size=50x50&set=set1',
    title: 'Excision of lesion of muscle',
    photo: null,
    state: 'Like New',
    price: '$61.87',
    uploaded_at: '2021-03-25T11:49:21Z',
    protected: false,
    likes: 13,
  },
  {
    id: 6,
    username: 'jelcome5',
    avatar: 'https://robohash.org/estquamreiciendis.png?size=50x50&set=set1',
    title: 'Marsupialization of splenic cyst',
    photo: null,
    state: 'Well Used',
    price: '$54.26',
    uploaded_at: '2021-03-20T10:46:19Z',
    protected: true,
    likes: 17,
  },
  {
    id: 7,
    username: 'bbortolini6',
    avatar: 'https://robohash.org/etvoluptatemdebitis.png?size=50x50&set=set1',
    title:
      'Closed reduction of fracture with internal fixation, unspecified site',
    photo: null,
    state: 'New',
    price: '$75.34',
    uploaded_at: '2021-05-25T16:06:36Z',
    protected: true,
    likes: 19,
  },
  {
    id: 8,
    username: 'hrounsefull7',
    avatar: 'https://robohash.org/doloremquiscorporis.png?size=50x50&set=set1',
    title: 'Other operations on pineal gland',
    photo: null,
    state: 'Well Used',
    price: '$97.97',
    uploaded_at: '2021-09-02T13:07:20Z',
    protected: true,
    likes: 20,
  },
  {
    id: 9,
    username: 'chutchinges8',
    avatar: 'https://robohash.org/estfacilisest.png?size=50x50&set=set1',
    title: 'Urinary diversion to intestine',
    photo: null,
    state: 'Used',
    price: '$41.15',
    uploaded_at: '2021-11-18T14:25:11Z',
    protected: false,
    likes: 4,
  },
  {
    id: 10,
    username: 'caingel9',
    avatar: 'https://robohash.org/nonnihilmagni.png?size=50x50&set=set1',
    title: 'Incision of palate',
    photo: null,
    state: 'Brand New',
    price: '$72.97',
    uploaded_at: '2021-10-03T15:01:14Z',
    protected: false,
    likes: 16,
  },
  {
    id: 11,
    username: 'hmusharta',
    avatar: 'https://robohash.org/delenitisintaut.png?size=50x50&set=set1',
    title: 'Open and other replacement of pulmonary valve with tissue graft',
    photo: null,
    state: 'Brand New',
    price: '$74.53',
    uploaded_at: '2021-10-19T11:42:23Z',
    protected: true,
    likes: 18,
  },
  {
    id: 12,
    username: 'gkenenb',
    avatar: 'https://robohash.org/deseruntvitaesunt.png?size=50x50&set=set1',
    title: 'Closed reduction of fracture with internal fixation, femur',
    photo: null,
    state: 'Like New',
    price: '$39.26',
    uploaded_at: '2021-06-27T01:13:21Z',
    protected: false,
    likes: 16,
  },
  {
    id: 13,
    username: 'sborriec',
    avatar: 'https://robohash.org/quimagnitenetur.png?size=50x50&set=set1',
    title: 'Other surgical induction of labor',
    photo: null,
    state: 'Used',
    price: '$10.96',
    uploaded_at: '2021-08-15T17:03:34Z',
    protected: false,
    likes: 2,
  },
  {
    id: 14,
    username: 'sclohiseyd',
    avatar: 'https://robohash.org/repudiandaequiaaut.png?size=50x50&set=set1',
    title: 'Unspecified operation on bone injury, radius and ulna',
    photo: null,
    state: 'Used',
    price: '$31.62',
    uploaded_at: '2021-05-01T09:52:30Z',
    protected: false,
    likes: 10,
  },
  {
    id: 15,
    username: 'slanone',
    avatar: 'https://robohash.org/etquisint.png?size=50x50&set=set1',
    title: 'Other operations on skin and subcutaneous tissue',
    photo: null,
    state: 'New',
    price: '$64.94',
    uploaded_at: '2021-08-19T02:09:14Z',
    protected: false,
    likes: 2,
  },
  {
    id: 16,
    username: 'ufernandof',
    avatar:
      'https://robohash.org/voluptatemprovidentullam.png?size=50x50&set=set1',
    title: 'Hair transplant',
    photo: null,
    state: 'New',
    price: '$46.21',
    uploaded_at: '2022-02-22T18:12:14Z',
    protected: true,
    likes: 11,
  },
  {
    id: 17,
    username: 'eklosterg',
    avatar:
      'https://robohash.org/quoconsequaturdelectus.png?size=50x50&set=set1',
    title: 'Heart revascularization by arterial implant',
    photo: null,
    state: 'Used',
    price: '$26.83',
    uploaded_at: '2021-09-29T13:54:19Z',
    protected: true,
    likes: 1,
  },
  {
    id: 18,
    username: 'ariellyh',
    avatar: 'https://robohash.org/occaecatieasuscipit.png?size=50x50&set=set1',
    title: 'Removal of mediastinal drain',
    photo: null,
    state: 'New',
    price: '$18.81',
    uploaded_at: '2021-07-25T07:18:08Z',
    protected: true,
    likes: 8,
  },
  {
    id: 19,
    username: 'naddsi',
    avatar:
      'https://robohash.org/magnivoluptatumdolorem.png?size=50x50&set=set1',
    title: 'Removal of intraluminal foreign body from nose without incision',
    photo: null,
    state: 'New',
    price: '$64.19',
    uploaded_at: '2021-08-09T08:30:24Z',
    protected: true,
    likes: 19,
  },
  {
    id: 20,
    username: 'egahanj',
    avatar: 'https://robohash.org/atutvoluptate.png?size=50x50&set=set1',
    title: 'Recession of tendon',
    photo: null,
    state: 'Like New',
    price: '$95.30',
    uploaded_at: '2021-06-05T11:45:59Z',
    protected: false,
    likes: 4,
  },
  {
    id: 21,
    username: 'mburgoinek',
    avatar: 'https://robohash.org/etenimoptio.png?size=50x50&set=set1',
    title: 'Revision of carotid sinus stimulation pulse generator',
    photo: null,
    state: 'Used',
    price: '$40.93',
    uploaded_at: '2021-11-28T08:39:00Z',
    protected: false,
    likes: 9,
  },
  {
    id: 22,
    username: 'skingdonl',
    avatar:
      'https://robohash.org/temporibuseosaccusantium.png?size=50x50&set=set1',
    title: 'Removal of foreign body from peritoneal cavity',
    photo: null,
    state: 'Brand New',
    price: '$52.03',
    uploaded_at: '2022-01-28T13:41:45Z',
    protected: false,
    likes: 7,
  },
  {
    id: 23,
    username: 'rglasm',
    avatar:
      'https://robohash.org/maximevoluptatemperspiciatis.png?size=50x50&set=set1',
    title: 'Cannulation of pancreatic duct',
    photo: null,
    state: 'New',
    price: '$90.27',
    uploaded_at: '2021-09-20T18:11:08Z',
    protected: false,
    likes: 11,
  },
  {
    id: 24,
    username: 'bhacquoiln',
    avatar: 'https://robohash.org/quosipsumquod.png?size=50x50&set=set1',
    title: 'Revision of previous repair of cranial and peripheral nerves',
    photo: null,
    state: 'Well Used',
    price: '$11.51',
    uploaded_at: '2021-04-28T12:50:02Z',
    protected: false,
    likes: 16,
  },
  {
    id: 25,
    username: 'cisleyo',
    avatar: 'https://robohash.org/quicorporissaepe.png?size=50x50&set=set1',
    title: 'Electromyogram of eye [EMG]',
    photo: null,
    state: 'Well Used',
    price: '$15.97',
    uploaded_at: '2021-05-15T15:31:36Z',
    protected: true,
    likes: 4,
  },
  {
    id: 26,
    username: 'mroloffp',
    avatar:
      'https://robohash.org/necessitatibusquiquia.png?size=50x50&set=set1',
    title: 'Other incision of bone without division, humerus',
    photo: null,
    state: 'New',
    price: '$25.23',
    uploaded_at: '2021-03-16T02:43:45Z',
    protected: true,
    likes: 20,
  },
  {
    id: 27,
    username: 'nmitchensonq',
    avatar: 'https://robohash.org/quisadipiscirerum.png?size=50x50&set=set1',
    title: 'Insertion of fixed bridge',
    photo: null,
    state: 'Brand New',
    price: '$63.13',
    uploaded_at: '2022-02-27T02:41:41Z',
    protected: true,
    likes: 4,
  },
  {
    id: 28,
    username: 'kthowr',
    avatar: 'https://robohash.org/oditaliquamut.png?size=50x50&set=set1',
    title: 'Non-invasive mechanical ventilation',
    photo: null,
    state: 'New',
    price: '$78.27',
    uploaded_at: '2021-03-26T13:46:13Z',
    protected: true,
    likes: 8,
  },
  {
    id: 29,
    username: 'eibles',
    avatar: 'https://robohash.org/doloreligendinon.png?size=50x50&set=set1',
    title: 'Referral for alcoholism rehabilitation',
    photo: null,
    state: 'Used',
    price: '$34.35',
    uploaded_at: '2022-01-21T01:46:33Z',
    protected: true,
    likes: 3,
  },
  {
    id: 30,
    username: 'lsilkt',
    avatar: 'https://robohash.org/etsitenim.png?size=50x50&set=set1',
    title: 'Sequestrectomy, patella',
    photo: null,
    state: 'New',
    price: '$73.58',
    uploaded_at: '2021-10-27T08:46:47Z',
    protected: true,
    likes: 12,
  },
  {
    id: 31,
    username: 'rcomolliu',
    avatar: 'https://robohash.org/veliteligendiet.png?size=50x50&set=set1',
    title: 'Biopsy of alveolus',
    photo: null,
    state: 'Like New',
    price: '$20.96',
    uploaded_at: '2021-03-07T18:24:22Z',
    protected: true,
    likes: 10,
  },
  {
    id: 32,
    username: 'vsergisonv',
    avatar:
      'https://robohash.org/temporealiquamsapiente.png?size=50x50&set=set1',
    title: 'Endoscopic control of gastric or duodenal bleeding',
    photo: null,
    state: 'Like New',
    price: '$43.62',
    uploaded_at: '2021-07-17T11:38:04Z',
    protected: false,
    likes: 2,
  },
  {
    id: 33,
    username: 'nservisw',
    avatar: 'https://robohash.org/facilisatquenemo.png?size=50x50&set=set1',
    title: 'Unspecified operation on bone injury, other specified bone',
    photo: null,
    state: 'Like New',
    price: '$17.77',
    uploaded_at: '2021-08-18T02:59:05Z',
    protected: false,
    likes: 19,
  },
  {
    id: 34,
    username: 'xdeverockx',
    avatar: 'https://robohash.org/voluptatemestlabore.png?size=50x50&set=set1',
    title: 'Open biopsy of soft tissue',
    photo: null,
    state: 'New',
    price: '$10.19',
    uploaded_at: '2021-11-01T12:08:52Z',
    protected: false,
    likes: 11,
  },
  {
    id: 35,
    username: 'mpoutony',
    avatar: 'https://robohash.org/undeaperiamcommodi.png?size=50x50&set=set1',
    title:
      'Microscopic examination of specimen from musculoskeletal system and of joint fluid, cell block and Papanicolaou smear',
    photo: null,
    state: 'Like New',
    price: '$86.94',
    uploaded_at: '2021-03-11T08:11:49Z',
    protected: false,
    likes: 11,
  },
  {
    id: 36,
    username: 'bbutlandz',
    avatar:
      'https://robohash.org/aliquidvoluptatemlaborum.png?size=50x50&set=set1',
    title: 'Other pyloroplasty',
    photo: null,
    state: 'Like New',
    price: '$21.09',
    uploaded_at: '2021-07-29T04:56:53Z',
    protected: false,
    likes: 4,
  },
  {
    id: 37,
    username: 'vhourston10',
    avatar: 'https://robohash.org/autemvelrerum.png?size=50x50&set=set1',
    title: 'Sinogram of chest wall',
    photo: null,
    state: 'Used',
    price: '$49.55',
    uploaded_at: '2021-03-24T06:03:39Z',
    protected: true,
    likes: 9,
  },
  {
    id: 38,
    username: 'rgai11',
    avatar: 'https://robohash.org/dolorelaboriosamfuga.png?size=50x50&set=set1',
    title: 'Application of external fixator device, femur',
    photo: null,
    state: 'Used',
    price: '$59.23',
    uploaded_at: '2021-12-24T08:20:10Z',
    protected: false,
    likes: 10,
  },
  {
    id: 39,
    username: 'bolley12',
    avatar:
      'https://robohash.org/veritatisoccaecatiquia.png?size=50x50&set=set1',
    title: 'Excision of bone for graft, femur',
    photo: null,
    state: 'Used',
    price: '$66.32',
    uploaded_at: '2021-03-20T00:01:04Z',
    protected: false,
    likes: 5,
  },
  {
    id: 40,
    username: 'ccowl13',
    avatar: 'https://robohash.org/nonofficiasoluta.png?size=50x50&set=set1',
    title: 'Partial splenectomy',
    photo: null,
    state: 'Brand New',
    price: '$5.24',
    uploaded_at: '2021-03-17T00:18:09Z',
    protected: true,
    likes: 0,
  },
  {
    id: 41,
    username: 'psundin14',
    avatar: 'https://robohash.org/remerroret.png?size=50x50&set=set1',
    title:
      'Other local excision or destruction of lesion of joint, other specified sites',
    photo: null,
    state: 'Well Used',
    price: '$34.77',
    uploaded_at: '2022-02-06T13:58:59Z',
    protected: false,
    likes: 12,
  },
  {
    id: 42,
    username: 'abernasek15',
    avatar: 'https://robohash.org/doloressaepedolor.png?size=50x50&set=set1',
    title: 'Open biopsy of seminal vesicles',
    photo: null,
    state: 'Like New',
    price: '$80.70',
    uploaded_at: '2022-02-21T06:49:56Z',
    protected: false,
    likes: 4,
  },
  {
    id: 43,
    username: 'nwhiting16',
    avatar: 'https://robohash.org/enimporrorerum.png?size=50x50&set=set1',
    title: 'Other repair or plastic operations on bone, patella',
    photo: null,
    state: 'Well Used',
    price: '$70.39',
    uploaded_at: '2021-04-11T18:45:13Z',
    protected: true,
    likes: 15,
  },
  {
    id: 44,
    username: 'acaverhill17',
    avatar:
      'https://robohash.org/dignissimosliberoquia.png?size=50x50&set=set1',
    title: 'Exenteration of orbit with therapeutic removal of orbital bone',
    photo: null,
    state: 'Used',
    price: '$17.40',
    uploaded_at: '2021-07-16T14:15:03Z',
    protected: false,
    likes: 18,
  },
  {
    id: 45,
    username: 'gbumpus18',
    avatar:
      'https://robohash.org/quaeratducimusnesciunt.png?size=50x50&set=set1',
    title: 'Other pleural biopsy',
    photo: null,
    state: 'Well Used',
    price: '$72.55',
    uploaded_at: '2021-12-20T05:44:01Z',
    protected: true,
    likes: 12,
  },
  {
    id: 46,
    username: 'tchittie19',
    avatar: 'https://robohash.org/minimasedsuscipit.png?size=50x50&set=set1',
    title: 'Laparoscopic radical abdominal hysterectomy',
    photo: null,
    state: 'New',
    price: '$69.57',
    uploaded_at: '2022-02-11T07:05:21Z',
    protected: true,
    likes: 15,
  },
  {
    id: 47,
    username: 'gvelten1a',
    avatar: 'https://robohash.org/quietrepellendus.png?size=50x50&set=set1',
    title: 'Pyeloscopy',
    photo: null,
    state: 'Used',
    price: '$31.21',
    uploaded_at: '2021-03-18T23:34:56Z',
    protected: false,
    likes: 7,
  },
  {
    id: 48,
    username: 'kstephens1b',
    avatar: 'https://robohash.org/rationenonitaque.png?size=50x50&set=set1',
    title: 'Biopsy of bone, patella',
    photo: null,
    state: 'New',
    price: '$44.41',
    uploaded_at: '2021-08-29T20:31:46Z',
    protected: true,
    likes: 4,
  },
  {
    id: 49,
    username: 'ltabourin1c',
    avatar: 'https://robohash.org/liberosintqui.png?size=50x50&set=set1',
    title:
      'Microscopic examination of peritoneal and retroperitoneal specimen, other microscopic examination',
    photo: null,
    state: 'Brand New',
    price: '$60.91',
    uploaded_at: '2021-12-31T23:36:35Z',
    protected: false,
    likes: 13,
  },
  {
    id: 50,
    username: 'hotson1d',
    avatar:
      'https://robohash.org/exercitationemdebitisdoloribus.png?size=50x50&set=set1',
    title: 'Open reduction of dislocation of ankle',
    photo: null,
    state: 'New',
    price: '$37.95',
    uploaded_at: '2021-10-04T22:30:15Z',
    protected: false,
    likes: 4,
  },
];
